name: Security audit
on:
    schedule: "weekly"
    push:
        paths:
            - '.github/workflows/audit.yml'
            - '**/Cargo.toml'
            - '**/Cargo.lock'
            - 'deny.toml'
jobs:
    security_audit:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: taiki-e/install-action@cargo-deny
            -   name: Scan for vulnerabilities
                run: cargo deny check
