name: Run tests

on:
    push:
        branches: [ main, development ]
    pull_request:
        branches: [ main, development ]

env:
    CARGO_TERM_COLOR: always

jobs:
    unit-tests:
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                rust: [ stable, nightly ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   run: rustup toolchain install ${{ matrix.rust }} --profile minimal
            -   uses: Swatinem/rust-cache@v2

            -   name: Run rustfmt checks
                run: cargo fmt --check

            -   name: Run clippy lints
                if: ${{ matrix.os != 'windows-latest' }}
                run: cargo clippy -- -D warnings

            -   name: Run unit tests
                run: cargo test
